### ISSUE TITLE
Mission editor - "Reload bindings" removing value

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#60] opened 2021-12-11 23:26 UTC
**Describe the bug**
When using a task like "event graph" it offers a button to "reload bindings"
If that task has a value like end_timer, that value will be gone after pressing the "reload bindings" button.

**To Reproduce**
1. Open some pre-made logic file with an "event graph" task
2. Check if the "event graph" has a value
3. Click on the button "reload bindings"

**Expected behavior**
No real idea what the button "reload bindings" does at this point, but straight up removing something doesn't seem right.

**Screenshots**
Before pressing the button
![MissionEditor_2021-12-12_00-19-01](https://user-images.githubusercontent.com/50502395/145694714-b2dc4651-9326-4adc-b386-6dbabdcb54cd.png)

After pressing the button
![MissionEditor_2021-12-12_00-19-09](https://user-images.githubusercontent.com/50502395/145694717-9660ac33-e791-433f-8259-0a829e84fecb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 10.0.19043
 - Version: SVN_7272.TC_4884 dx11

**Comment by lukaasm** [comment] 2021-12-12 17:25
It's not a bug, it seems that the pointed logic file no longer uses binding with that name.

What are bindings?
Bindings allow fields within internal logic nodes to be overridden from external sources.

![image](https://user-images.githubusercontent.com/48881/145722555-5cd214e7-9637-46c1-9c75-8910af7c4e2a.png)

Then when the node field is bound to external data it is marked as:
![image](https://user-images.githubusercontent.com/48881/145722579-7f86e1ba-2bed-4d43-870f-a4c779e7127c.png)

And now when someone instantiated logic flow that exposes some bindable fields from other logic files or Lua script, they can modify exposed fields to their liking:
![image](https://user-images.githubusercontent.com/48881/145722695-77f770c4-759a-4a20-8961-9a231f58747f.png)
(Reload bindings just re-populates fields exposed by logic file)

**Closed** 2021-12-12 23:04 UTC
Labels: invalid
